module.exports = {
  contentTypeWithNumericKeys: {
    uid: "test_content_type",
    title: "Test Content Type",
    description: "A test content type with numeric keys",
    schema_type: "content_type",
    schema: [
      {
        uid: "title",
        display_name: "Title",
        data_type: "text",
        mandatory: true,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "123field",
        display_name: "123 Field",
        data_type: "text",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "description",
        display_name: "Description",
        data_type: "text",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "456field",
        display_name: "456 Field",
        data_type: "number",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "number",
      },
    ],
  },

  contentTypeWithNestedNumericKeys: {
    uid: "nested_numeric_test",
    title: "Nested Numeric Test",
    description: "A test content type with nested numeric keys",
    schema_type: "content_type",
    schema: [
      {
        uid: "title",
        display_name: "Title",
        data_type: "text",
        mandatory: true,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "group1",
        display_name: "Group 1",
        data_type: "group",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "group",
        schema: [
          {
            uid: "789nested",
            display_name: "789 Nested",
            data_type: "text",
            mandatory: false,
            multiple: false,
            non_localizable: false,
            display_type: "text",
          },
          {
            uid: "012deep",
            display_name: "012 Deep",
            data_type: "text",
            mandatory: false,
            multiple: false,
            non_localizable: false,
            display_type: "text",
          },
        ],
      },
    ],
  },

  contentTypeWithNumericBlockKeys: {
    uid: "numeric_block_test",
    title: "Numeric Block Test",
    description: "A test content type with numeric block keys",
    schema_type: "content_type",
    schema: [
      {
        uid: "title",
        display_name: "Title",
        data_type: "text",
        mandatory: true,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "modular_blocks",
        display_name: "Modular Blocks",
        data_type: "blocks",
        mandatory: false,
        multiple: true,
        non_localizable: false,
        display_type: "blocks",
        blocks: [
          {
            uid: "111block",
            display_name: "111 Block",
            reference_to: null,
            schema: [
              {
                uid: "block_title",
                display_name: "Block Title",
                data_type: "text",
                mandatory: true,
                multiple: false,
                non_localizable: false,
                display_type: "text",
              },
            ],
          },
          {
            uid: "222block",
            display_name: "222 Block",
            reference_to: null,
            schema: [
              {
                uid: "block_content",
                display_name: "Block Content",
                data_type: "text",
                mandatory: false,
                multiple: false,
                non_localizable: false,
                display_type: "text",
              },
            ],
          },
          {
            uid: "valid_block",
            display_name: "Valid Block",
            reference_to: null,
            schema: [
              {
                uid: "block_field",
                display_name: "Block Field",
                data_type: "text",
                mandatory: false,
                multiple: false,
                non_localizable: false,
                display_type: "text",
              },
            ],
          },
        ],
      },
    ],
  },

  contentTypeWithMixedKeys: {
    uid: "mixed_keys_test",
    title: "Mixed Keys Test",
    description: "A test content type with mixed valid and invalid keys",
    schema_type: "content_type",
    schema: [
      {
        uid: "title",
        display_name: "Title",
        data_type: "text",
        mandatory: true,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "validField",
        display_name: "Valid Field",
        data_type: "text",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
      {
        uid: "999invalid",
        display_name: "999 Invalid",
        data_type: "text",
        mandatory: false,
        multiple: false,
        non_localizable: false,
        display_type: "text",
      },
    ],
  },
};
