name: Node.js CI

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3.5.3

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}

      # Clean Dependencies
      - name: Clean Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      # Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Project
      - name: Build the Project
        run: npm run build --if-present

      # Run Tests
      - name: Run Tests
        run: npm test
        env:
          TOKEN: ${{secrets.TOKEN}}
          TOKEN_WITH_NO_CT: ${{secrets.TOKEN_WITH_NO_CT}}
          APIKEY: ${{secrets.APIKEY}}
          APIKEY_WITH_NO_CT: ${{secrets.APIKEY_WITH_NO_CT}}
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
          REGION: ${{secrets.REGION}}
          TOKENTYPE: ${{secrets.TOKENTYPE}}
          BRANCH: ${{secrets.BRANCH}}
