# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          rm -rf node_modules package-lock.json
          npm i
      - name: Run tests with coverage
        run: npm run test:unit:report:json
        env:
          TOKEN: ${{secrets.TOKEN}}
          TOKEN_WITH_NO_CT: ${{secrets.TOKEN_WITH_NO_CT}}
          APIKEY: ${{secrets.APIKEY}}
          APIKEY_WITH_NO_CT: ${{secrets.APIKEY_WITH_NO_CT}}
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
          REGION: ${{secrets.REGION}}
          TOKENTYPE: ${{secrets.TOKENTYPE}}
          BRANCH: ${{secrets.BRANCH}}

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: coverage/clover.xml
