name: Publish package to npmjs registry
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - name: Update npm
        run: npm install -g npm@latest
      - name: Release
        run: npm publish --access public
        env:
          npm_config_registry: https://registry.npmjs.org/
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - run: npm ci
      - name: Update npm
        run: npm install -g npm@latest
      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
